---
kind: pipeline
name: test-on-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:latest
  commands:
  - apt-get update && apt-get upgrade -y && apt-get install -y 
    build-essential pkg-config libc6-dev m4 g++-multilib 
    autoconf libtool ncurses-dev unzip git python python-zmq 
    zlib1g-dev wget curl bsdmainutils automake
  - ./zcutil/build.sh -j$(nproc)
  #- ./zcutil/fetch-params.sh
  #- ./qa/zcash/full_test_suite.py --list-stages
  #- ./qa/zcash/full_test_suite.py btest
  #- ./qa/zcash/full_test_suite.py gtest
  #- ./qa/zcash/full_test_suite.py sec-hard
  #- ./qa/zcash/full_test_suite.py no-dot-so
  #- ./qa/zcash/full_test_suite.py util-test
  #- ./qa/zcash/full_test_suite.py secp256k1
  #- ./qa/zcash/full_test_suite.py libsnark
  #- ./qa/zcash/full_test_suite.py univalue
  #- ./qa/zcash/full_test_suite.py rpc

---
kind: pipeline
name: test-on-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: ubuntu:latest
  commands:
  - apt-get update && apt-get upgrade -y && apt-get install -y 
    build-essential pkg-config libc6-dev m4 g++-multilib 
    autoconf libtool ncurses-dev unzip git python python-zmq 
    zlib1g-dev wget curl bsdmainutils automake
  - ./zcutil/build.sh -j$(nproc)

---
kind: pipeline
name: test-on-windoze

platform:
  os: windows
  arch: amd64

steps:
- name: build
  image: ubuntu:latest
  commands:
  - apt-get update && apt-get upgrade -y && apt-get install -y 
    build-essential pkg-config libc6-dev m4 g++-multilib 
    autoconf libtool ncurses-dev unzip git python python-zmq 
    zlib1g-dev wget curl bsdmainutils automake
  - ./zcutil/build.sh -j$(nproc)