name: CI

on: [push]

jobs:
  build_linux_x64:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python-zmq zlib1g-dev wget curl bsdmainutils automake python-pip -y
        sudo pip install pyblake2
    - name: build
      run: ./zcutil/build.sh -j$(nproc)
    - name: test
      run: |
        nproc
        ./zcutil/fetch-params.sh
        ./qa/zcash/full_test_suite.py --list-stages
        ./qa/zcash/full_test_suite.py btest
        ./qa/zcash/full_test_suite.py gtest
        ./qa/zcash/full_test_suite.py sec-hard
        ./qa/zcash/full_test_suite.py no-dot-so
        ./qa/zcash/full_test_suite.py util-test
        ./qa/zcash/full_test_suite.py secp256k1
        ./qa/zcash/full_test_suite.py libsnark
        ./qa/zcash/full_test_suite.py univalue
        ./qa/zcash/full_test_suite.py rpc


