name: CI

on: [pull_request]

jobs:
  linux_x64_build:
    runs-on: ubuntu-16.04
    steps:
     - name: checkout
       uses: actions/checkout@master
     - name: build
       run: docker build --build-arg TARGET_SHA=${{ github.sha }} -t FOOOOO -f .github/jobs/build/debian/Dockerfile.newcommit .
  linux_x64_btest:
    runs-on: ubuntu-16.04
    needs: linux_x64_build
    steps:
     - name: btest
       run: docker images
