name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python python-zmq zlib1g-dev wget curl bsdmainutils automake -y 
    - name: test
      run: ./qa/zcash/full_test_suite.py
    - name: build
      run: ./zcutil/build.sh -j$(nproc)
    - name: deploy
      run: echo "This is the depployment step"  
