name: CI

on: [push, pull_request]

jobs:
  linux_x64_btest:
    runs-on: ubuntu-16.04
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    - name: btest
      run: docker run zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352 ./qa/zcash/full_test_suite.py btest
  linux_x64_gtest:
    runs-on: ubuntu-16.04
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    - name: gtest
      run: docker run zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352 ./qa/zcash/full_test_suite.py gtest
  linux_x64_sec-hard:
    runs-on: ubuntu-16.04
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    - name: sec-hard
      run: docker run zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352 ./qa/zcash/full_test_suite.py sec-hard
  linux_x64_not-dot-so:
    runs-on: ubuntu-16.04
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    - name: no-dot-so
      run: docker run zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352 ./qa/zcash/full_test_suite.py no-dot-so
  linux_x64_util-test:
    runs-on: ubuntu-16.04
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    - name: util-test
      run: docker run zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352 ./qa/zcash/full_test_suite.py util-test
  linux_x64_secp256k1:
    runs-on: ubuntu-16.04
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    - name: secp256k1
      run: docker run zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352 ./qa/zcash/full_test_suite.py secp256k1
  linux_x64_libsnark:
    runs-on: ubuntu-16.04
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    - name: libsnark
      run: docker run zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352 ./qa/zcash/full_test_suite.py libsnark
  linux_x64_unival:
    runs-on: ubuntu-16.04
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    - name: univalue
      run: docker run zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352 ./qa/zcash/full_test_suite.py univalue
  linux_x64_rpc:
    runs-on: ubuntu-16.04
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    - name: rpc
      run: docker run zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352 ./qa/zcash/full_test_suite.py rpc
