name: CI

on: [push]

jobs:
  linux_x64:

    # TODO add build matrix for supported OS
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: install-dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install build-essential pkg-config libc6-dev m4 g++-multilib autoconf libtool ncurses-dev unzip git python3 python3-zmq zlib1g-dev wget curl bsdmainutils automake python3-pip python3-setuptools -y
        #sudo pip install pyblake2 pyflakes
        #sudo pip3 install pyutil pyblake2 pyflakes simplejson
        sudo pip3 install pyflakes pyblake2 pyzmq pyutil python-qpid-proton simplejson
    #- name: pyflakes
    #  run: pyflakes qa src zcutil        
    - name: build
      run: ./zcutil/build.sh -j$(nproc)
    - name: fetch-params
      run: ./zcutil/fetch-params.sh
    - name: list-stages
      run: ./qa/zcash/full_test_suite.py --list-stages
    - name: btest
      run: ./qa/zcash/full_test_suite.py btest
    - name: gtest
      run: ./qa/zcash/full_test_suite.py gtest
    - name: sec-hard
      run: ./qa/zcash/full_test_suite.py sec-hard
    - name: no-dot-so
      run: ./qa/zcash/full_test_suite.py no-dot-so
    - name: util-test
      run: ./qa/zcash/full_test_suite.py util-test
    - name: secp256k1
      run: ./qa/zcash/full_test_suite.py secp256k1
    - name: libsnark
      run: ./qa/zcash/full_test_suite.py libsnark
    - name: univalue
      run: ./qa/zcash/full_test_suite.py univalue
    - name: rpc
      run: ./qa/zcash/full_test_suite.py rpc  

# TODO ARM cross-compile
# TODO MacOS native build
# TODO Windows cross-compile
# TODO Run tests on native platforms