name: CI

on: [pull_request]

jobs:
  linux_x64_build:
    runs-on: ubuntu-16.04
    steps:
     - name: checkout
       uses: actions/checkout@master
     - name: build
       run: docker build -t zingolabs/zcashdebian -f .github/jobs/build/debian/Dockerfile.newcommit .
     - name: extract_build_artifacts
       run: docker create 
  linux_x64_btest:
    runs-on: ubuntu-16.04
    needs: linux_x64_build
    steps:
     - name: btest
       run: docker images
