name: CI

on: [push]

jobs:
  linux_x64:

    # TODO add build matrix for supported OS
    runs-on: ubuntu-16.04
    
    steps:
    - uses: docker://zingolabs/zcashdebian:87c1df780db87a9b8d44ea7b0d1a30ee4f47f352
    #- name: pyflakes
    #  run: pyflakes qa src zcutil        
    - name: build
      run: ./make
    - name: list-stages
      run: ./qa/zcash/full_test_suite.py --list-stages
    - name: btest
      run: ./qa/zcash/full_test_suite.py btest
    - name: gtest
      run: ./qa/zcash/full_test_suite.py gtest
    - name: sec-hard
      run: ./qa/zcash/full_test_suite.py sec-hard
    - name: no-dot-so
      run: ./qa/zcash/full_test_suite.py no-dot-so
    - name: util-test
      run: ./qa/zcash/full_test_suite.py util-test
    - name: secp256k1
      run: ./qa/zcash/full_test_suite.py secp256k1
    - name: libsnark
      run: ./qa/zcash/full_test_suite.py libsnark
    - name: univalue
      run: ./qa/zcash/full_test_suite.py univalue
    - name: rpc
      run: ./qa/zcash/full_test_suite.py rpc
