name: CI

on: [pull_request]

jobs:
  linux_x64_build:
    runs-on: ubuntu-16.04
    steps:
     - name: checkout
       uses: actions/checkout@master
     - name: build
       run: docker build -t zingolabs/zcashdebian -f .github/jobs/build/debian/Dockerfile.newcommit .
     - name: sanity_check_docker_images
       run: docker images
     - name: save_build_image
       working-directory: ${HOME}
       run: docker save -o zingolabs_zcashdebian.tar zingolabs/zcashdebian
     - name: look
       run: echo ${HOME} && ls -la ${HOME}
  linux_x64_btest:
    runs-on: ubuntu-16.04
    needs: linux_x64_build
    steps:
     - name: checkout
       uses: actions/checkout@master
     - name: sanity_check_docker_images
       run: docker images
     - name: look
       run: echo ${HOME} && ls -la ${HOME}
     - name: load_build_image
       working-directory: ${HOME}
       run: docker load -i zingolabs_zcashdebian.tar
     - name: run_image
       run: docker run zingolabs_zcashdebian
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
