name: CI

on: [pull_request]

jobs:
  linux_x64_build:
    runs-on: ubuntu-16.04
    steps:
     - name: checkout
       uses: actions/checkout@master
     - name: look and see
       run: pwd && ls -la .github/actions/
     - name: build
       uses: ./.github/actions/build
       with:
         entrypoint: /bin/echo
         args: ${{ github.sha }} is the sha.
       run: docker run
