name: CI

on: [pull_request]

jobs:
  linux_x64_build:
    runs-on: ubuntu-16.04
    steps:
     - name: checkout
       uses: actions/checkout@master
     - name: build
       uses: ./.github/actions/test
  linux_x64_btest:
    runs-on: ubuntu-16.04
    needs: linux_x64_build
    steps:
     - name: btest
       uses: ./.github/actions/test
       with:
         args: "btest"
